module.exports = {
  verbose: true,
  styleLoader: 'style-loader!css-loader!sass-loader',

  scripts: {
    'foundation.core': true, 
    'foundation.abide': true,
    'foundation.accordion': true,
    'foundation.accordionMenu': true,
    'foundation.drilldown': true,
    'foundation.dropdown': true,
    'foundation.dropdownMenu': true,
    'foundation.equalizer': true,
    'foundation.interchange': true,
    'foundation.magellan': true,
    'foundation.offcanvas': true,
    'foundation.orbit': true,
    'foundation.responsiveMenu': true,
    'foundation.responsiveToggle': true,
    'foundation.reveal': true,
    'foundation.slider': true,
    'foundation.sticky': true,
    'foundation.tabs': true,
    'foundation.toggler': true,
    'foundation.tooltip': true,
    'foundation.util.box': true,
    'foundation.util.keyboard': true,
    'foundation.util.mediaQuery': true,
    'foundation.util.motion': true,
    'foundation.util.nest': true,
    'foundation.util.timerAndImageLoader': true,
    'foundation.util.touch': true,
    'foundation.util.triggers': true
  },
  styles: {
    'mixins': true,

    'normalize': true,
    'print': true,
    'glyphicons': true,

    'scaffolding': true,
    'type': true,
    'code': true,
    'grid': true,
    'tables': true,
    'forms': true,
    'buttons': true,

    'component-animations': true,
    'dropdowns': true,
    'button-groups': true,
    'input-groups': true,
    'navs': true,
    'navbar': true,
    'breadcrumbs': true,
    'pagination': true,
    'pager': true,
    'labels': true,
    'badges': true,
    'jumbotron': true,
    'thumbnails': true,
    'alerts': true,
    'progress-bars': true,
    'media': true,
    'list-group': true,
    'panels': true,
    'wells': true,
    'responsive-embed': true,
    'close': true,

    'modals': true,
    'tooltip': true,
    'popovers': true,
    'carousel': true,

    'utilities': true,
    'responsive-utilities': true
  }
};
